/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114103-gda39a19aad-20240311"
#endif /* AVUTIL_FFVERSION_H */
