#pragma once

#include "Client_Defines.h"
#include "Character.h"
#include "Actor.h"

BEGIN(Client)

class CPlayer final : public CCharacter
{
private:
	CPlayer(ID3D11Device* pDevice, ID3D11DeviceContext* pContext, const wstring& strPrototypeTag);
	CPlayer(const CPlayer& rhs);
	virtual ~CPlayer() = default;

public:
	virtual HRESULT Initialize_Prototype() override;
	virtual HRESULT Initialize(void* pArg) override;
	virtual void Priority_Tick(_float fTimeDelta) override;
	virtual void Tick(_float fTimeDelta) override;
	virtual void Late_Tick(_float fTimeDelta) override;
	virtual HRESULT Render() override;


private:
	HRESULT Ready_Components();
	HRESULT Ready_PartObjects();

private:
	CActor<CPlayer>* m_pActor = { nullptr };

public:
	/* 원형객체를 생성한다. */
	static CPlayer* Create(ID3D11Device* pDevice, ID3D11DeviceContext* pContext, const wstring& strPrototypeTag);

	/* 사본객체를 생성한다. */
	virtual CGameObject* Clone(void* pArg) override;
	virtual CGameObject* Pool() override;

	virtual void Free() override;

public:
	enum Player_State
	{
		Player_Empowered_Idle,
		Player_Empowered_IdlePose,
		Player_Empowered_MeleeCombo_01,
		Player_Empowered_MeleeCombo_02,
		Player_Empowered_MeleeCombo_03,
		Player_Empowered_Shot,
		Player_Empowered_SlamGround,
		Player_Empowered_Start,
		Player_Empowered_Stop,
		Player_Empowered_Winchester_IdleFire,
		Player_Empowered_Winchester_Start,
		Player_Empowered_Winchester_Stop,
		Player_Empowered_Winchester_v2_IdleLoop,
		cover_high_reload_01,
		cover_high_start_f_01,
		cover_high_start_l_01,
		cover_high_start_r_01,
		cover_low_reload_01,
		cover_low_start_f_01,
		cover_low_start_l_01,
		cover_low_start_r_01,
		Player_SlamDown_v2,
		Player_SlamDown_v3,
		Player_SlamDown_ManHero,
		MeleeSwap_01,
		MeleeSwap_02,
		Player_Leap_Long_Recovery,
		Player_Leap_Shorter_Recovery,
		WhipPull,
		IdleLoop,
		IdlePose,
		Interaction_Slide_Sequence,
		InteractionClimb100,
		InteractionClimb100_02,
		InteractionClimb200,
		InteractionClimb300,
		InteractionClimb450,
		InteractionDoorPush,
		InteractionJumpDown100,
		InteractionJumpDown200,
		InteractionJumpDown300,
		InteractionJumpDown300_Alt,
		InteractionPushButton,
		InteractionVault100,
		InteractionVault200,
		Player_BeamWalk_Idle_Add,
		Player_BeamWalk_IdlePose,
		Player_BeamWalk_IdlePose_02,
		Player_BeamWalk_JumpOver,
		Player_BeamWalk_Loop,
		Player_BeamWalk_Loop_01,
		Player_BeamWalk_Loop_02,
		Player_BeamWalk_Start,
		Player_BeamWalk_Stop,
		Player_BeamWalk_Unbalance,
		Player_Cargo_LedgeStrafe_R_Custom_01,
		Player_CartRide_JumpOff_01,
		Player_CartRide_Loop,
		Player_CartRide_LoopAdditive,
		Player_CartRide_Start,
		Player_CrouchUnder_End,
		Player_CrouchUnder_Gate,
		Player_CrouchUnder_Loop,
		Player_CrouchUnder_Start,
		Player_CrouchUseCables,
		Player_DrivingCart,
		Player_InspectFlameBelcher,
		Player_Interaction_Destroy,
		Player_Interaction_Glamour,
		Player_Interaction_SmallLever,
		Player_InteractionBattery,
		Player_InteractionClimbRope_Idle_Add_01,
		Player_InteractionClimbRope_IdlePose,
		Player_InteractionClimbRope_Idle_Add_02,
		Player_InteractionClimbRope_IdlePose_02,
		Player_InteractionClimbRope_Loop_01,
		Player_InteractionClimbRope_Loop_02,
		Player_InteractionClimbRope_Start,
		Player_InteractionClimbRope_Stop,
		Player_InteractionDoor_Open,
		Player_InteractionGlamour_Activate,
		Player_InteractionGlamour_End,
		Player_InteractionLadder_Up_IdlePose,
		Player_InteractionLadder_Up_Loop,
		Player_InteractionLadder_Up_Start,
		Player_InteractionLadder_Up_Stop,
		Player_InteractionPlank_DodgeR_01,
		Player_InteractionPlank_Up_Idle_Add_01,
		Player_InteractionPlank_Up_IdlePose_01,
		Player_InteractionPlank_Up_Idle_Add_02,
		Player_InteractionPlank_Up_IdlePose_02,
		Player_InteractionPlank_Up_Loop_01,
		Player_InteractionPlank_Up_Loop_02,
		Player_InteractionPlank_Up_Start,
		Player_InteractionPlank_Up_Stop,
		Player_InteractionPull,
		Player_InteractionPull_Rock_End,
		Player_InteractionPull_Rock_Idle,
		Player_InteractionPull_Rock_Loop,
		Player_InteractionPull_Unable,
		Player_InteractionPull_WindUp,
		Player_InteractionPush_Rock_End,
		Player_InteractionPush_Rock_Idle,
		Player_InteractionPush_Rock_Loop,
		Player_InteractionPush_Rock_Pull_to_Push,
		Player_InteractionPush_Rock_Push_to_Pull,
		Player_InteractionPush_Rock_Start,
		Player_InteractionPush_Unable,
		Player_InteractionPush_WindUp,
		Player_InteractionRope_Down_Loop,
		Player_InteractionRope_Down_Start,
		Player_InteractionRope_Down_Stop,
		Player_InteractionRotateValve_01,
		Player_InteractionWhipPull,
		Player_InteractionWhipSwing,
		Player_LedgeStrafe_Alt_L_Idle_Add,
		Player_LedgeStrafe_Alt_L_IdlePose,
		Player_LedgeStrafe_Alt_L_Loop,
		Player_LedgeStrafe_Alt_L_Start,
		Player_LedgeStrafe_Alt_L_Stop,
		Player_LedgeStrafe_Alt_L_WalkOver,
		Player_LedgeStrafe_Alt_L_WalkUnder,
		Player_LedgeStrafe_Alt_R_Idle_Add,
		Player_LedgeStrafe_Alt_R_IdlePose,
		Player_LedgeStrafe_Alt_R_Loop,
		Player_LedgeStrafe_Alt_R_Start,
		Player_LedgeStrafe_Alt_R_Stop,
		Player_LedgeStrafe_L_Idle,
		Player_LedgeStrafe_L_Loop,
		Player_LedgeStrafe_L_Start,
		Player_LedgeStrafe_L_Stop,
		Player_LedgeStrafe_R_Idle,
		Player_LedgeStrafe_R_Loop,
		Player_LedgeStrafe_R_Start,
		Player_LedgeStrafe_R_Stop,
		Player_LedgeStrafe_StepSlip_L,
		Player_LongJump_2m,
		Player_LongJump_4m,
		Player_LongJump_4m_down,
		Player_LongJumpStill_2m,
		Player_LongJumpStill_4m,
		Player_LongJumpStill_4m_down,
		Player_OpenLootCrate,
		Player_OpenLootCrate_NEW,
		Player_OpenLootCrate_Small,
		Player_ResetMachine,
		Player_SqueezeThrough_L_Idle,
		Player_SqueezeThrough_L_Loop,
		Player_SqueezeThrough_L_Start,
		Player_SqueezeThrough_L_Stop,
		Player_SqueezeThrough_R_Idle,
		Player_SqueezeThrough_R_Loop,
		Player_SqueezeThrough_R_Start,
		Player_SqueezeThrough_R_Stop,
		Player_Workbench_WeaponUpgrade_01,
		Player_ZipLine_Loop,
		Player_ZipLine_Start,
		Player_ZipLine_Start_to_Loop,
		Player_ZipLine_Stop,
		Player_BeamWalk_BJ_01,
		Player_BeamWalk_Cargo_01_Idle_01,
		Player_BeamWalk_Cargo_01_Idle_02,
		Player_BeamWalk_Cargo_01_Idle_03,
		Player_BeamWalk_Cargo_01_Idle_04,
		Player_BeamWalk_Cargo_01_Loop_01,
		Player_BeamWalk_Cargo_01_Loop_02,
		Player_BeamWalk_Cargo_01_Loop_03,
		Player_BeamWalk_Cargo_01_Start,
		Player_BeamWalk_Cargo_01_Stop,
		Player_BeamWalk_Forest_01,
		Player_BeamWalk_Tesla_02,
		Player_InteractionClimbMove,
		Player_LongJump_Canyon_01,
		Player_MoF_LedgeStrafe_L_RockFall,
		Player_SqueezeTrough_Dick_01,
		Player_SqueezeTrough_Raid_01_IdlePose_01,
		Player_SqueezeTrough_Raid_01_IdlePose_02,
		Player_SqueezeTrough_Raid_01_IdlePose_03,
		Player_SqueezeTrough_Raid_01_IdlePose_04,
		Player_SqueezeTrough_Raid_01_IdlePose_05,
		Player_SqueezeTrough_Raid_01_IdlePose_06,
		Player_SqueezeTrough_Raid_01_Loop_L_01,
		Player_SqueezeTrough_Raid_01_Loop_L_02,
		Player_SqueezeTrough_Raid_01_Loop_R_01,
		Player_SqueezeTrough_Raid_01_Loop_R_02,
		Player_SqueezeTrough_Raid_01_Loop_R_03,
		Player_SqueezeTrough_Raid_01_Shift_L_R,
		Player_SqueezeTrough_Raid_01_Start,
		Player_SqueezeTrough_Raid_01_Stop,
		Player_SqueezeTrough_Raid_01_Stuck_R_01,
		Player_SqueezeTrough_Tesla_01,
		Player_Tesla_LedgeStrafe_L,
		Player_Tesla_LedgeStrafe_L_02,
		Player_ZipLine_OF_01_Loop,
		Player_ZipLine_OF_01_Start,
		Player_ZipLine_OF_01_Start_to_Loop,
		Player_ZipLine_OF_01_Stop,
		MeleeCombo_04,
		MeleeFollowUp,
		MeleeInPlace_9Hit,
		Player_CrowdThrough_L_Loop,
		Player_CrowdThrough_L_Start,
		Player_CrowdThrough_L_Stop,
		Player_EnergyWhip_CloseRange_01,
		Player_EnergyWhip_Leap,
		Player_EnergyWhip_LeapShort,
		Player_EnergyWhip_LongRange,
		Player_EnergyWhip_Pull,
		Player_GlamourAdditive,
		Player_HitHeavy_F_5m,
		Player_SqueezeThrough_Alt_L_IdlePose,
		Player_SqueezeThrough_Alt_L_Loop,
		Player_SqueezeThrough_Alt_L_Start,
		Player_SqueezeThrough_Alt_L_Stop,
		Player_SqueezeThrough_Alt_R_IdlePose,
		Player_SqueezeThrough_Alt_R_Loop,
		Player_SqueezeThrough_Alt_R_Start,
		Player_SqueezeThrough_Alt_R_Stop,
		Player_SqueezeThrough_L_Idle_Add,
		Player_SqueezeThrough_R_Idle_Add,
		Player_Turn_L90,
		Player_Turn_R90,
		Player_WhipSlam,
		Revolver_EmpoweredShot,
		Revolver_Hip_AO_F,
		LF_Idle_Pose,
		Uppercut_03_TEMP,
		Uppercut_04_TEMP,
		Uppercut_05v3_TEMP,
		UppercutAOE,
		DodgeBlink_B_03,
		DodgeBlink_CCW,
		DodgeBlink_CW,
		DodgeBlink_L_03,
		DodgeBlink_R_03
	};
};

END


